### PR TITLE
Rxswift

### PR DESCRIPTION
**Pull request by palfvin**
Hey Jared,

I'd like to go over this with you before you merge it. I left the first WIP commit that we did in here so that you could see the changes I made since we last worked together.

Pete

### CODE REVIEW

**Comment by jwfriese** [comment]
Hey Pete. I tried running the app on my machine, and could not get the auth methods stream to trigger the segue into the rest of the app.

**Comment by palfvin** [comment]
Sorry.  I'll look at it first thing in the morning. I couldn't authenticate
myself and I thought it had something to do with my permissions.

**Comment by palfvin** [comment]
What do you think about putting in a basic UI test?

**Comment by jwfriese** [comment]
I'd certainly support it  👍 
I would have waited to chat with you about it in the morning. I'll spend the next two days up in Glendale, though, and wanted to make sure you were aware of what I saw!

**Comment by jwfriese** [comment]
@palfvin - Works great, Pete. I'm rebasing away that WIP commit and merging right now!

In the future, please include the Tracker stories in commit messages so that we can track things in history. Thanks so much for the work here, I am excited to take this project in a reactive direction 👍

**Comment by palfvin** [comment]
Hey Jared,

FYI, I'm still getting my head around the various issues with replay/share
and how to test them and think there is a problem with unnecessary second
calls to the auth methods API. Expect a couple more updates ....

Pete

**Pull request merged**
